{{- if .Values.images.frontend.replicaCount }}
apiVersion: v1
kind: Service
metadata:
    name: "{{ template "fullname" . }}-frontend"
    labels:
        app: {{ template "name" . }}
        chart: {{ template "chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
        component: "frontend"
spec:
    ports:
        -   protocol: TCP
            port: {{ .Values.images.frontend.servicePort }}
            targetPort: http
    selector:
        app: {{ template "name" . }}
        release: {{ .Release.Name }}
        component: "frontend"
  {{- end }}