pullPolicy: "IfNotPresent"

couchdbServiceName: "couchdb-svc-couchdb.couch"
couchdbPortNumber: 5984
couchdbCredentialsBase64: "" # defiend in the config

ingressIP: "" # defined during helm install
#tls:
#    -   hosts:
#            -   example.com
#        refName: tls-example-com

images:
    backend:
        repository: "docker.taktik.be/icure-backend"
        tag: "" # helm install
        replicaCount: 3
        javaOpts: "" # config
        memoryRequest: "2300M"
        memoryLimit: "2300M"
        cpuRequest: 100m
        cpuLimit: 2
        servicePort: 16043
        debug: true
        env:
            ICURE_COUCHDB_USERNAME: "" # config
            ICURE_COUCHDB_PASSWORD: "" # config
            ICURE_COUCHDB_PREFIX: "icure-__"
            ICURE_COUCHDB_ENFORCE: "TRUE"
            ICURE_MIKRONO_SUPERUSER: "icure"
            ICURE_MIKRONO_SUPERTOKEN: "" # config
            ICURE_MIKRONO_APPLICATIONTOKEN: "" # config
    frontend:
        repository: "docker.taktik.be/icure-frontend"
        tag:
        replicaCount: 1
        memoryRequest: "64M"
        memoryLimit: "512M"
        cpuRequest: 50m
        cpuLimit: 500m
        servicePort: 80
        env: {}